---
name: SkyGrid
description: Survival in SkyGrid
author: EdoGaming
main: EdoGaming\SkyGrid\SkyGrid
version: 2.0
api: [1.2.0, 2.0.0, 3.0.0, 4.0.0]
permissions:
  SkyGrid.interaction:
    description: izinkan player untuk berinteraksi di pulau orang tanpa harus jadi 1 pulau
    default: op
...
